/**
 * Generate the per-theme CSS files used by `example/index.html`.
 *
 * Each file is one @marianmeres/design-tokens bundled theme run through the
 * Bootstrap Reboot bridge: it sets the `--app-color-*` design tokens (consumed
 * by the example's inline layout AND remapped onto the chart's own
 * `--trend-chart-*` variables) plus the `--bs-*` variables (consumed by
 * reboot.css). Light mode lands on `:root`, dark mode on `:root.dark`.
 *
 * Because every file targets `:root`, only one may be active at a time — the
 * page swaps a single `<link>`'s href to switch themes, and toggles the `dark`
 * class on `<html>` for light/dark. No selector rewriting needed.
 *
 * Run:  deno task example:themes
 */
// deno-lint-ignore-file no-import-prefix -- example-only tooling: design-tokens is
// deliberately NOT in the package import map (the library itself has zero deps).
import { generateThemedCss } from "jsr:@marianmeres/design-tokens@^1/reboot";
import { getBundledTheme } from "jsr:@marianmeres/design-tokens@^1/themes";

/** CSS variable prefix — generic for a standalone example. */
const PREFIX = "app-";

/**
 * Curated subset of the bundled themes, chosen to span the range (neutral,
 * vivid, warm, dark-leaning) and — because the chart's value zones are painted
 * with the `success` / `warning` / `accent` / `destructive` intents — to keep
 * those four visibly distinct. Swap this for `bundledThemeNames` (same module
 * as `getBundledTheme`) to emit all of them. The first entry is the page default.
 */
const THEMES = [
	"slateTealOcean",
	"indigoAmber",
	"emeraldPink",
	"mistIndigoFjord",
	"monokaiGreen",
	"redSky",
	"taupeRoseBlush",
	"zinc",
];

/** camelCase → kebab-case (matches the package's own css filenames). */
const toKebab = (s: string): string => s.replace(/([A-Z])/g, "-$1").toLowerCase();

const dir = new URL(".", import.meta.url).pathname;

for (const name of THEMES) {
	const schema = getBundledTheme(name);
	if (!schema) {
		console.warn(`! unknown theme "${name}" — skipped`);
		continue;
	}
	const header =
		`/*\n * @marianmeres/design-tokens "${name}" theme + Bootstrap Reboot bridge.\n` +
		` * Generated by example/themes/_generate.ts — do not edit by hand.\n` +
		` * Light on :root, dark on :root.dark; prefix "${PREFIX}".\n */\n`;
	const css = generateThemedCss(schema, PREFIX, { prettierIgnore: true });
	await Deno.writeTextFile(`${dir}${toKebab(name)}.css`, header + css);
}

console.log(
	`Generated ${THEMES.length} theme files in example/themes/ (prefix "${PREFIX}").`,
);
